witmotion:
  ros__parameters:
    port: ttyUSB2
    baud_rate: 115200 # baud
    polling_interval: 5 # ms
    timeout_ms: 150 # ms
    restart_service_name: /restart_imu/wt31n
    imu_publisher:
      topic_name: /imu/wt31n
      frame_id: wt31n_link
      use_native_orientation: false
      measurements:
        acceleration:
            enabled: true
            covariance: [ 0.0112,    0.0,       0.0,
                          0.0,         0.0081,  0.0,
                          0.0,         0.0,       0.0128 ]
        angular_velocity:
            enabled: false
            covariance: [ 0.1199,    0.0,       0.0,
                          0.0,         0.5753,  0.0,
                          0.0,         0.0,       0.0267 ]
        orientation:
            enabled: true
            covariance: [ 0.0457,    0.0,       0.0,
                          0.0,         0.0655,  0.0,
                          0.0,         0.0,       0.0      ]
    temperature_publisher:
      enabled: false
      topic_name: /temperature/wt31n
      frame_id: wt31n_link
      from_message: angular_vel # acceleration, angular_vel, orientation, magnetometer
      variance: 0.01829
      coefficient: 1.0 # Linear calibration parameters: coefficient
      addition: 0.0 # and addendum
####### NOT USE ########
    magnetometer_publisher:
      enabled: false
      topic_name: /magnetometer/wt31n
      frame_id: compass
      coefficient: 0.00000001 # Linear calibration parameters: coefficient
      addition: 0.0 # and addendum
      covariance:
        [0.000000187123, 0.0, 0.0, 0.0, 0.000000105373, 0.0, 0.0, 0.0, 0.000000165816]
    barometer_publisher:
      enabled: false
      topic_name: /barometer/wt31n
      frame_id: base_link
      variance: 0.001
      coefficient: 1.0 # Linear calibration parameters: coefficient
      addition: 0.0 # and addendum
    altimeter_publisher:
      enabled: false
      topic_name: /altitude/wt31n
      coefficient: 1.0 # Linear calibration parameters: coefficient
      addition: 0.0 # and addendum
    orientation_publisher:
      enabled: false
      topic_name: /orientation/wt31n
    gps_publisher:
      enabled: false
      navsat_fix_frame_id: world
      navsat_fix_topic_name: /gps
      navsat_altitude_topic_name: /gps_altitude
      navsat_satellites_topic_name: /gps_satellites
      navsat_variance_topic_name: /gps_variance
      ground_speed_topic_name: /gps_ground_speed
    rtc_publisher:
      enabled: false
      topic_name: /witmotion_clock
