imu_filter_wtgahrs1:
  ros__parameters:
    use_mag: true
    use_magnetic_field_msg : true
    world_frame: "enu"
    publish_tf: true
    reverse_tf : false
    fixed_frame : "odom"
    publish_acc: false
    use_imu_heading: false
    frequency: 50.0
    gain: 0.1
