<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.405" />
    <xacro:property name="base_width" value="0.329" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="base_offset_origin_x" value="0.17" />
    <xacro:property name="base_offset_origin_y" value="0" />
    <xacro:property name="base_offset_origin_z" value="0.13" />
    <xacro:property name="wheel_radius" value="0.25" />
    <xacro:property name="wheel_length" value="0.04" />
    <xacro:property name="wheel_offset_origin_y" value="0.05" />

    <link name="body_link">
        <visual>
            <geometry>
                <mesh filename="file://$(find rhacobot_description)/meshes/chassis.stl"
                    scale="0.001 0.001 0.001" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin
                xyz="${base_offset_origin_x - (base_length /2)} ${base_offset_origin_y} ${base_offset_origin_z - (base_height/2)}"
                rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" l="${gazebo_drift_factor * base_length}"
            w="${gazebo_drift_factor * base_width}" h="${gazebo_drift_factor * base_height}"
            xyz="${base_offset_origin_x - (base_length /2)} ${base_offset_origin_y} ${base_offset_origin_z - (base_height/2)}"
            rpy="0 0 0" />
    </link>

    <joint name="base_body_joint" type="continuous">
        <parent link="base_link" />
        <child link="body_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <link name="right_wheel_link">
        <visual>
            <geometry>
                <mesh filename="file://$(find rhacobot_description)/meshes/wheel.stl"
                    scale="0.001 0.001 0.001" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi} 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 -${wheel_offset_origin_y}  0" rpy="${pi / 2.0} 0 0" />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${gazebo_drift_factor * wheel_radius}"
            h="${gazebo_drift_factor * wheel_length}"
            xyz="0 -${wheel_offset_origin_y}  0" rpy="${pi / 2.0} 0 0" />
    </link>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="0 -${base_width / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <mesh filename="file://$(find rhacobot_description)/meshes/wheel.stl"
                    scale="0.001 0.001 0.001" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi} 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 -${wheel_offset_origin_y}  0" rpy="${pi / 2.0} 0 0" />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${gazebo_drift_factor * wheel_radius}"
            h="${gazebo_drift_factor * wheel_length}"
            xyz="0 -${wheel_offset_origin_y}  0" rpy="${pi / 2.0} 0 0" />
    </link>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="0 ${base_width  / 2.0} 0" rpy="${pi} 0 0" />
        <axis xyz="0 1 0" />
    </joint>

</robot>